<a href="https://colab.research.google.com/github/eclipse1228/ML_lib/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [42]:
np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
sample_df = pd.read_csv('sample.csv')
sample_np=np.array(sample_df)
pd.DataFrame(sample_np)
# 넘파이는 컬럼명이 없다.

0  1
0   1  2
1   3  4
2   2  5
3   5  6
4   3  2
5   1  1
6   2  6
7   5  7
8   6  8
9   7  4
10  7  7
11  8  3
12  9  7
13  3  9
14  2  2
15  1  3
16  2  6
17  2  4
18  3  3

In [9]:
sample_df.columns # colum names

Index(['Var_1', 'Var_2'], dtype='object')

In [10]:
pd.DataFrame(sample_np, columns = sample_df.columns) # 컬럼명 바꾸기~

Var_1  Var_2
0       1      2
1       3      4
2       2      5
3       5      6
4       3      2
5       1      1
6       2      6
7       5      7
8       6      8
9       7      4
10      7      7
11      8      3
12      9      7
13      3      9
14      2      2
15      1      3
16      2      6
17      2      4
18      3      3

In [11]:
sample_np

array([[1, 2],
       [3, 4],
       [2, 5],
       [5, 6],
       [3, 2],
       [1, 1],
       [2, 6],
       [5, 7],
       [6, 8],
       [7, 4],
       [7, 7],
       [8, 3],
       [9, 7],
       [3, 9],
       [2, 2],
       [1, 3],
       [2, 6],
       [2, 4],
       [3, 3]])

In [12]:
sample_np[0]

array([1, 2])

In [17]:
sample_np[0, 1]

2

In [21]:
sample_np[0:2, 0:2]

array([[1, 2],
       [3, 4]])

In [16]:
sample_np[:,1]

array([2, 4, 5, 6, 2, 1, 6, 7, 8, 4, 7, 3, 7, 9, 2, 3, 6, 4, 3])

In [23]:
# 배열 연산

In [25]:
np_a = np.array([[1,3],[0,-2]])
np_a

array([[ 1,  3],
       [ 0, -2]])

In [26]:
# 더하기 (빼기 나누기 다 됨 )
np_a +10

array([[11, 13],
       [10,  8]])

In [30]:
np_b= np.array([[1,0],[0,1]])
np_a + np_b

array([[ 2,  3],
       [ 0, -1]])

In [31]:
# 곱셈
np_a * np_b

array([[ 1,  0],
       [ 0, -2]])

In [32]:
# 행렬 곱
np_a @ np_b

array([[ 1,  3],
       [ 0, -2]])

In [34]:
# random.xxx() 함수
# np.random.randint(11) # 0~ 10 사이 숫자
np.random.randint(50,71) # 50~ 71

54

In [35]:
np.random.randint(50,71,5) # 5개 고르기

array([50, 57, 52, 57, 64])

In [36]:
# 목록중 랜덤으로 선택 (복원 추출 (같은 값 등장))
np.random.choice(['red','green','while','blue','purple'], size = 3)

array(['green', 'blue', 'green'], dtype='<U6')

In [ ]:
## 중복 x
np.random.choice(['red','green','while','blue','purple'], size = 3 , replace=False)

In [38]:
# arange() 함수
# 일련의 숫자를 만든다.
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
np.arange(1,11,2) # 2칸씩 띄워 받기

array([1, 3, 5, 7, 9])

In [40]:
# linspace() 함수
np.linspace(1,10,4) # 1부터 10까지 균등한 간격으로 나눈 4개의 지점

array([ 1.,  4.,  7., 10.])